# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.cache/wt [current_project]
set_property parent.project_path F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo f:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/MUX.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/zero_counter.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/shift_right.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/shift_left.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/comp_exp.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/comp.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/CLA.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/subnormals.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Signout.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/selector.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Round.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/normals.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/mux_mix_normal.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/mux_adder.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/mixed.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/demux_numbers_type.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Adder.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Special_cases.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Vector.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/preadder.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Block_norm.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/Block_Adder.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/keypad.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/displ7seg.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/debounce.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/adder_substraction.vhd
  F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/sources_1/new/main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/constraints/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/University/UTCluj/An3/Semestrul2/SSC/Proiect/FloatingNumberAdder/FloatingNumberAdder.srcs/constraints/Nexys4DDR_Master.xdc]


synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
